sudo: required
dist: trusty
language: cpp

services:
  - docker

branches:
  only:
    - master
    - develop

before_install:
  - docker build -t travis-build -f tools/Dockerfile .

script:
  - docker run --rm travis-build tools/checkstyle.sh $TRAVIS_COMMIT_RANGE
  - docker run --rm travis-build /bin/bash -c "mkdir build-clang-tidy && cd build-clang-tidy && CXX=clang++-7 CC=clang-7 cmake -GNinja .. && ninja clang-tidy"
  - docker run --rm travis-build /bin/bash -c "mkdir build-clang-debug && cd build-clang-debug && CXX=clang++-7 CC=clang-7 cmake -DCMAKE_BUILD_TYPE=Debug -GNinja .. && ninja && python ../tools/post_build_ninja_summary.py && ctest --output-on-failure && ./benchmark"
  - docker run --rm travis-build /bin/bash -c "mkdir build-clang-release && cd build-clang-release && CXX=clang++-7 CC=clang-7 cmake -DCMAKE_BUILD_TYPE=Release -GNinja .. && ninja && python ../tools/post_build_ninja_summary.py && ctest --output-on-failure && ./benchmark"
  - docker run --rm travis-build /bin/bash -c "mkdir build-gcc-debug && cd build-gcc-debug && CXX=g++-8 CC=gcc-8 cmake -DCMAKE_BUILD_TYPE=Debug -GNinja .. && ninja && python ../tools/post_build_ninja_summary.py && ctest --output-on-failure && ./benchmark"
  - docker run --rm travis-build /bin/bash -c "mkdir build-gcc-release && cd build-gcc-release && CXX=g++-8 CC=gcc-8 cmake -DCMAKE_BUILD_TYPE=Release -GNinja .. && ninja && python ../tools/post_build_ninja_summary.py && ctest --output-on-failure && ./benchmark"